language: node_js

deploy:
  provider: npm
  email: $EMAIL
  api_key:
    secure: $API_KEY
  on:
    tags: true
    repo: thejoaov/react-native-template-thejoaov-redux
branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/
