name: Publish to NPM
on: push
jobs: 
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Publishing to NPM
        uses: mikeal/merge-release@v4.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
